os:
  - linux
  - osx
matrix:
  allow_failures:
    - os: osx
language: c
git:
  submodules: false
install: bash -ex scripts/travis-ci.sh poly
script: ruby scripts/update_suite.rb
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/86c0d96b8abfc23dbc97
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
