name: uploadSarif

on:
  push:
  pull_request:

jobs:
  generate-Sarif:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 4.12.0 # matches opam lock file
          # don't add any other because they won't be used

    runs-on: ${{ matrix.os }}
    permissions:
       security-events: write
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up OCaml ${{ matrix.ocaml-compiler }}
          env:
            # otherwise setup-ocaml pins non-locked dependencies
            # https://github.com/ocaml/setup-ocaml/issues/166
            OPAMLOCKED: locked
          uses: ocaml/setup-ocaml@v2
          with:
            ocaml-compiler: ${{ matrix.ocaml-compiler }}

        - name: Install dependencies
          run: opam install . --deps-only --locked

        - name: Build
          run: ./make.sh nat
        - name: Run Goblint
          run: ./goblint --sarif -o GitHubSarif.sarif tests/regression/02-base/02-simple_assignments.c
        - name: Upload SARIF file
            uses: github/codeql-action/upload-sarif@v1
            with:
              # Path to SARIF file relative to the root of the repository
              sarif_file: GitHubSarif.sarif
# upload-Sarif:
 #   runs-on: ubuntu-latest
 #   permissions:
  #    security-events: write
  #  steps:
      # This step checks out a copy of your repository.
   #   - name: Checkout repository
   #     uses: actions/checkout@v2
   #   - name: Upload SARIF file
    #    uses: github/codeql-action/upload-sarif@v1
    #    with:
          # Path to SARIF file relative to the root of the repository
      #   sarif_file: GitHubSarif.sarif
